export const POKEDEX_ENTRIES = [
    "A strange seed was planted on its back at birth.\nThe plant sprouts and grows with this POKéMON.",
    "When the bulb on its back grows large, it appears\nto lose the ability to stand on its hind legs.",
    "The plant blooms when it is absorbing solar\nenergy. It stays on the move to seek sunlight.",
    "Obviously prefers hot places. When it rains, steam\nis said to spout from the tip of its tail.",
    "When it swings its burning tail, it elevates the\ntemperature to unbearably high levels.",
    "Spits fire that is hot enough to melt boulders.\nKnown to cause forest fires unintentionally.",
    "After birth, its back swells and hardens into a\nshell. Powerfully sprays foam from its mouth.",
    "Often hides in water to stalk unwary prey. For\nswimming fast, it moves its ears to maintain balance.",
    "A brutal POKéMON with pressurized water jets on its\nshell. They are used for high speed tackles.",
    "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
    "This POKéMON is vulnerable to attack while its\nshell is soft, exposing its weak and tender body.",
    "In battle, it flaps its wings at high speed to\nrelease highly toxic dust into the air.",
    "Often found in forests, eating leaves.\nIt has a sharp venomous stinger on its head.",
    "Almost incapable of moving, this POKéMON can only\nharden its shell to protect itself from predators.",
    "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
    "A common sight in forests and woods. It flaps its\nwings at ground level to kick up blinding sand.",
    "Very protective of its sprawling territorial area,\nthis POKéMON will fiercely peck at any intruder.",
    "When hunting, it skims the surface of water at high\nspeed to pick off unwary prey such as MAGIKARP.",
    "Bites anything when it attacks. Small and very\nquick, it is a common sight in many places.",
    "It uses its whis­ kers to maintain its balance.\nIt apparently slows down if they are cut off.",
    "It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.",
    "With its huge and magnificent wings, it can keep aloft\nwithout ever having to land for rest.",
    "Moves silently and stealthily. Eats the eggs of\nbirds, such as PIDGEY and SPEAROW, whole.",
    "It is rumored that the ferocious warning markings\non its belly differ from area to area.",
    "When several of these POKéMON gather, their\nelectricity could build and cause lightning storms.",
    "Its long tail serves as a ground to protect itself from its own high-voltage power.",
    "Burrows deep underground in arid locations\nfar from water. It only emerges to hunt for food.",
    "Curls up into a spiny ball when threatened. It\ncan roll while curled up to attack or escape.",
    "Although small, its venomous barbs render this\nPOKéMON dangerous. The female has smaller horns.",
    "The female's horn develops slowly. Prefers physical\nattacks such as clawing and biting.",
    "Its hard scales provide strong protection. It\nuses its hefty bulk to execute powerful moves.",
    "Stiffens its ears to sense danger. The larger its\nhorns, the more powerful its secreted venom.",
    "An aggressive POKéMON that is quick to attack.\nThe horn on its head secretes a powerful venom.",
    "It uses its powerful tail in battle to smash,\nconstrict, then break the prey's bones.",
    "Its magical and cute appeal has many admirers.\nIt is rare and found only in certain areas.",
    "A timid fairy POKéMON that is rarely seen. It\nwill run and hide the moment it senses people.",
    "At the time of birth, it has just one tail.\nThe tail splits from its tip as it grows older.",
    "Very smart and very vengeful. Grabbing one of\nits many tails could result in a 1000-year curse.",
    "When its huge eyes light up, it sings a mysteriously\nsoothing melody that lulls its enemies to sleep.",
    "The body is soft and rubbery. When angered, it will\nsuck in air and inflate itself to an enormous size.",
    "Forms colonies in perpetually dark places. Uses\nultrasonic waves to identify and approach targets.",
    "Once it strikes, it will not stop draining energy\nfrom the victim even if it gets too heavy to fly.",
    "During the day, it keeps its face buried in the\nground. At night, it wanders around sowing its seeds.",
    "The fluid that oozes from its mouth isn't drool.\nIt is a nectar that is used to attract prey.",
    "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.",
    "Burrows to suck tree roots. The mushrooms on its\nback grow by draw­ ing nutrients from the bug host.",
    "A host-parasite pair in which the parasite mushroom\nhas taken over the host bug. Prefers damp places.",
    "Lives in the shadows of tall trees where it\neats insects. It is attracted by light at night.",
    "The dustlike scales covering its wings are color-coded to indicate the kinds of poison it has.",
    "Lives about one yard underground where it feeds on\nplant roots. It sometimes appears above ground.",
    "A team of DIGLETT triplets. It triggers huge\nearthquakes by burrowing 60 miles underground.",
    "It washes its face regularly to keep the coin on its forehead spotless. It doesn’t get along with Galarian Meowth.",
    "Although its fur has many admirers, it is tough to\nraise as a pet because of its fickle meanness.",
    "While lulling its enemies with its vacant look, this\nwily POKéMON will use psychokinetic powers.",
    "Often seen swim­ ming elegantly by lake shores. It\nis often mistaken for the Japanese monster, Kappa.",
    "Extremely quick to anger. It could be docile one\nmoment then thrashing away the next instant.",
    "Always furious and tenacious to boot. It will not\nabandon chasing its quarry until it is caught.",
    "Very protective of its territory. It will bark and\nbite to repel intruders from its space.",
    "A POKéMON that has been admired since the past\nfor its beauty. It runs agilely as if on wings.",
    "Its newly grown legs prevent it from running. It\nappears to prefer swimming than trying to stand.",
    "Capable of living in or out of water. When out\nof water, it sweats to keep its body slimy.",
    "An adept swimmer at both the front crawl and breast\nstroke. Easily overtakes the best human swimmers.",
    "Using its ability to read minds, it will identify\nimpending danger and TELEPORT to safety.",
    "It emits special alpha waves from its body that\ninduce headaches just by being close by.",
    "Its brain can out­ perform a super­ computer.\nIts intelligence quotient is said to be 5,000.",
    "Loves to build its muscles. It trains in all\nstyles of martial arts to become even stronger.",
    "Its muscular body is so powerful, it must wear a power\nsave belt to be able to regulate its motions.",
    "Using its heavy muscles, it throws powerful punches\nthat can send the victim clear over the horizon.",
    "A carnivorous POKéMON that traps and eats bugs.\nIt uses its root feet to soak up needed moisture.",
    "It spits out POISONPOWDER to immobilize the\nenemy and then finishes it with a spray of ACID.",
    "Said to live in huge colonies deep in jungles,\nalthough no one has ever returned from there.",
    "Drifts in shallow seas. Anglers who hook them by\naccident are often punished by its stinging acid.",
    "The tentacles are normally kept short. On hunts,\nthey are extended to ensnare and immobilize prey.",
    "Found in fields and mountains. Mistaking them\nfor boulders, people often step or trip on them.",
    "Rolls down slopes to move. It rolls over any obstacle\nwithout slowing or changing its direction.",
    "Its boulder-like body is extremely hard. It can\neasily withstand dynamite blasts without damage.",
    "Its hooves are 10 times harder than diamonds. It can\ntrample anything completely flat in little time.",
    "Very competitive, this POKéMON will chase anything\nthat moves fast in the hopes of racing it.",
    "Incredibly slow and dopey. It takes 5 seconds\nfor it to feel pain when under attack.",
    "The SHELLDER that is latched onto SLOWPOKE's tail\nis said to feed on the host's left over scraps.",
    "Uses anti-gravity to stay suspended. Appears without\nwarning and uses THUNDER WAVE and similar moves.",
    "Formed by several MAGNEMITEs linked together. They\nfrequently appear when sunspots flare up.",
    "The sprig of green onions it holds is its\nweapon. It is used much like a metal sword.",
    "A bird that makes up for its poor flying with its\nfast foot speed. Leaves giant footprints.",
    "Uses its three brains to execute complex plans.\nWhile two heads sleep, one head stays awake.",
    "The protruding horn on its head is very hard.\nIt is used for bashing through thick ice.",
    "Stores thermal energy in its body. Swims at a\nsteady 8 knots even in intensely cold waters.",
    "Appears in filthy areas. Thrives by sucking up\npolluted sludge that is pumped out of factories.",
    "Thickly covered with a filthy, vile sludge. It\nis so toxic, even its footprints contain poison.",
    "Its hard shell repels any kind of attack.\nIt is vulnerable only when its shell is open.",
    "When attacked, it launches its horns in quick\nvolleys. Its innards have never been seen.",
    "Almost invisible, this gaseous POKéMON cloaks\nthe target and puts it to sleep without notice.",
    "Because of its ability to slip through block\nwalls, it is said to be from an­ other dimension.",
    "Under a full moon, this POKéMON likes to mimic\nthe shadows of people and laugh at their fright.",
    "As it grows, the stone portions of its body harden\nto become similar to a diamond, but colored black.",
    "Puts enemies to sleep then eats their dreams.\nOccasionally gets sick from eating bad dreams.",
    "When it locks eyes with an enemy, it will use a mix of\nPSI moves such as HYPNOSIS and CONFUSION.",
    "Its pincers are not only powerful weapons, they are\nused for balance when walking sideways.",
    "The large pincer has 10000 hp of crushing power.\nHowever, its huge size makes it unwieldy to use.",
    "Usually found in power plants. Easily mistaken\nfor a POKé BALL, they have zapped many people.",
    "It stores electric energy under very high pressure.\nIt often explodes with little or no provocation.",
    "Often mistaken for eggs. When disturbed,\nthey quickly gather and attack in swarms.",
    "Legend has it that on rare occasions, one of its heads\nwill drop off and continue on as an EXEGGCUTE.",
    "Because it never removes its skull helmet, no one\nhas ever seen this POKéMON's real face.",
    "The bone it holds is its key weapon. It throws the\nbone skillfully like a boomerang to KO targets.",
    "When in a hurry, its legs lengthen progressively.\nIt runs smoothly with extra long, loping strides.",
    "While apparently doing nothing, it fires punches in\nlightning fast volleys that are impossible to see.",
    "Its tongue can be extended like a chameleon's. It\nleaves a tingling sensation when it licks enemies.",
    "Because it stores several kinds of toxic gases in\nits body, it is prone to exploding without warning.",
    "Where two kinds of poison gases meet, 2 KOFFINGs\ncan fuse into a WEEZING over many years.",
    "A POKéMON with a one-track mind. Once it charges, \nit won't stop running until it falls asleep.",
    "Protected by an armor-like hide, it is capable of\nliving in molten lava of 3,600 degrees.",
    "A rare and elusive POKéMON that is said to bring\nhappiness to those who manage to get it.",
    "The whole body is swathed with wide vines that are\nsimilar to sea­ weed. Its vines shake as it walks.",
    "The infant rarely ventures out of its mother's\nprotective pouch until it is 3 years old.",
    "Known to shoot down flying bugs with precision\nblasts of ink from the surface of the water.",
    "Capable of swim­ ming backwards by rapidly flapping\nits wing-like pectoral fins and stout tail.",
    "Its tail fin billows like an elegant ballroom\ndress, giving it the nickname of the Water Queen.",
    "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.",
    "If its body is torn, it can grow back if the red core remains. The core flashes at midnight.",
    "Its central core glows with the seven colors of\nthe rainbow. Some people value the core as a gem.",
    "If interrupted while it is miming, it will\nslap around the offender with its broad hands.",
    "With ninja-like agility and speed, it can create the\nillusion that there is more than one.",
    "It seductively wiggles its hips as it walks. It\ncan cause people to dance in unison with it.",
    "Normally found near power plants, they can wander\naway and cause major blackouts in cities.",
    "Its body always burns with an orange glow that\nenables it to hide perfectly among flames.",
    "If it fails to crush the victim in its pincers,\nit will swing it around and toss it hard.",
    "When it targets an enemy, it charges furiously\nwhile whipping its body with its long tails.",
    "In the distant past, it was somewhat stronger\nthan the horribly weak descendants that exist today.",
    "Once it begins to rampage, a GYARADOS will burn everything down, even in a harsh storm.",
    "A POKéMON that has been over­ hunted almost to\nextinction. It can ferry people across the water.",
    "Capable of copying an enemy's genetic code to instantly\ntransform itself into a duplicate of the enemy.",
    "Its genetic code is irregular. It may mutate if\nit is exposed to radiation from element STONEs.",
    "Lives close to water. Its long tail is ridged\nwith a fin which is often mistaken for a mermaid's.",
    "It accumulates negative ions in the atmosphere to\nblast out 10000- volt lightning bolts.",
    "When storing thermal energy in its body, its\ntemperature could soar to over 1600 degrees.",
    "A POKéMON that consists entirely of programming\ncode. Capable of moving freely in cyberspace.",
    "Although long extinct, in rare cases, it can be\ngenetically resurrected from fossils.",
    "A prehistoric POKéMON that died out when its\nheavy shell made it impossible to catch prey.",
    "A POKéMON that was resurrected from a fossil\nfound in what was once the ocean floor eons ago.",
    "Its sleek shape is perfect for swim­ ming. It slashes\nprey with its claws and drains the body fluids.",
    "A Pokémon that roamed the skies in the dinosaur era. Its teeth are like saw blades.",
    "Very lazy. Just eats and sleeps. As its rotund\nbulk builds, it becomes steadily more slothful.",
    "A legendary bird POKéMON that is said to appear to\ndoomed people who are lost in icy mountains.",
    "A legendary bird POKéMON that is said to appear\nfrom clouds while dropping enormous lightning bolts.",
    "Known as the legendary bird of fire. Every flap\nof its wings creates a dazzling flash of flames.",
    "Long considered a mythical POKéMON until recently\nwhen a small colony was found living underwater.",
    "A mystical POKéMON that exudes a gentle aura.\nHas the ability to change climate conditions.",
    "An extremely rarely seen marine POKéMON.\nIts intelligence is said to match that of humans.",
    "It was created by a scientist after years of horrific\ngene splicing and DNA engineering experiments.",
    "So rare that it is still said to be a mirage by\nmany experts. Only a few people have seen it worldwide."
];