export const POKEMONS = [
  {
    number: 1,
    name: "bulbasaur",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    stage: 1,
    colors: ["green"],
    habitat: "grassland",
    height: 7,
    weight: 69,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 2,
    name: "ivysaur",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
    stage: 2,
    colors: ["green"],
    habitat: "grassland",
    height: 10,
    weight: 130,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 3,
    name: "venusaur",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
    stage: 3,
    colors: ["green"],
    habitat: "grassland",
    height: 20,
    weight: 1000,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 4,
    name: "charmander",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
    stage: 1,
    colors: ["orange"],
    habitat: "mountain",
    height: 6,
    weight: 85,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 5,
    name: "charmeleon",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
    stage: 2,
    colors: ["orange"],
    habitat: "mountain",
    height: 11,
    weight: 190,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 6,
    name: "charizard",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
    stage: 3,
    colors: ["orange"],
    habitat: "mountain",
    height: 17,
    weight: 905,
    type_1: "fire",
    type_2: "flying",
  },
  {
    number: 7,
    name: "squirtle",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
    stage: 1,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 5,
    weight: 90,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 8,
    name: "wartortle",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
    stage: 2,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 10,
    weight: 225,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 9,
    name: "blastoise",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
    stage: 3,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 16,
    weight: 855,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 10,
    name: "caterpie",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
    stage: 1,
    colors: ["green"],
    habitat: "forest",
    height: 3,
    weight: 29,
    type_1: "bug",
    type_2: "none",
  },
  {
    number: 11,
    name: "metapod",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
    stage: 2,
    colors: ["green"],
    habitat: "forest",
    height: 7,
    weight: 99,
    type_1: "bug",
    type_2: "none",
  },
  {
    number: 12,
    name: "butterfree",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
    stage: 3,
    colors: ["white", "purple"],
    habitat: "forest",
    height: 11,
    weight: 320,
    type_1: "bug",
    type_2: "flying",
  },
  {
    number: 13,
    name: "weedle",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
    stage: 1,
    colors: ["brown"],
    habitat: "forest",
    height: 3,
    weight: 32,
    type_1: "bug",
    type_2: "poison",
  },
  {
    number: 14,
    name: "kakuna",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "forest",
    height: 6,
    weight: 100,
    type_1: "bug",
    type_2: "poison",
  },
  {
    number: 15,
    name: "beedrill",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
    stage: 3,
    colors: ["yellow"],
    habitat: "forest",
    height: 10,
    weight: 295,
    type_1: "bug",
    type_2: "poison",
  },
  {
    number: 16,
    name: "pidgey",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
    stage: 1,
    colors: ["brown"],
    habitat: "forest",
    height: 3,
    weight: 18,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 17,
    name: "pidgeotto",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
    stage: 2,
    colors: ["brown"],
    habitat: "forest",
    height: 11,
    weight: 300,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 18,
    name: "pidgeot",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
    stage: 3,
    colors: ["brown"],
    habitat: "forest",
    height: 15,
    weight: 395,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 19,
    name: "rattata",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
    stage: 1,
    colors: ["purple"],
    habitat: "grassland",
    height: 3,
    weight: 35,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 20,
    name: "raticate",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
    stage: 2,
    colors: ["brown"],
    habitat: "grassland",
    height: 7,
    weight: 185,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 21,
    name: "spearow",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
    stage: 1,
    colors: ["brown"],
    habitat: "rough-terrain",
    height: 3,
    weight: 20,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 22,
    name: "fearow",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
    stage: 2,
    colors: ["brown"],
    habitat: "rough-terrain",
    height: 12,
    weight: 380,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 23,
    name: "ekans",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
    stage: 1,
    colors: ["purple"],
    habitat: "grassland",
    height: 20,
    weight: 69,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 24,
    name: "arbok",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
    stage: 2,
    colors: ["purple"],
    habitat: "grassland",
    height: 35,
    weight: 650,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 25,
    name: "pikachu",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "forest",
    height: 4,
    weight: 60,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 26,
    name: "raichu",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "forest",
    height: 8,
    weight: 300,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 27,
    name: "sandshrew",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "rough-terrain",
    height: 6,
    weight: 120,
    type_1: "ground",
    type_2: "none",
  },
  {
    number: 28,
    name: "sandslash",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "rough-terrain",
    height: 10,
    weight: 295,
    type_1: "ground",
    type_2: "none",
  },
  {
    number: 29,
    name: "nidoran-f",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png",
    stage: 1,
    colors: ["blue"],
    habitat: "grassland",
    height: 4,
    weight: 70,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 30,
    name: "nidorina",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png",
    stage: 2,
    colors: ["blue"],
    habitat: "grassland",
    height: 8,
    weight: 200,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 31,
    name: "nidoqueen",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png",
    stage: 3,
    colors: ["blue"],
    habitat: "grassland",
    height: 13,
    weight: 600,
    type_1: "poison",
    type_2: "ground",
  },
  {
    number: 32,
    name: "nidoran-m",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png",
    stage: 1,
    colors: ["purple"],
    habitat: "grassland",
    height: 5,
    weight: 90,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 33,
    name: "nidorino",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png",
    stage: 2,
    colors: ["purple"],
    habitat: "grassland",
    height: 9,
    weight: 195,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 34,
    name: "nidoking",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png",
    stage: 3,
    colors: ["purple"],
    habitat: "grassland",
    height: 14,
    weight: 620,
    type_1: "poison",
    type_2: "ground",
  },
  {
    number: 35,
    name: "clefairy",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png",
    stage: 1,
    colors: ["pink"],
    habitat: "mountain",
    height: 6,
    weight: 75,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 36,
    name: "clefable",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png",
    stage: 2,
    colors: ["pink"],
    habitat: "mountain",
    height: 13,
    weight: 400,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 37,
    name: "vulpix",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png",
    stage: 1,
    colors: ["orange"],
    habitat: "grassland",
    height: 6,
    weight: 99,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 38,
    name: "ninetales",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "grassland",
    height: 11,
    weight: 199,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 39,
    name: "jigglypuff",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
    stage: 1,
    colors: ["pink"],
    habitat: "grassland",
    height: 5,
    weight: 55,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 40,
    name: "wigglytuff",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png",
    stage: 2,
    colors: ["pink"],
    habitat: "grassland",
    height: 10,
    weight: 120,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 41,
    name: "zubat",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png",
    stage: 1,
    colors: ["purple"],
    habitat: "cave",
    height: 8,
    weight: 75,
    type_1: "poison",
    type_2: "flying",
  },
  {
    number: 42,
    name: "golbat",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png",
    stage: 2,
    colors: ["purple"],
    habitat: "cave",
    height: 16,
    weight: 550,
    type_1: "poison",
    type_2: "flying",
  },
  {
    number: 43,
    name: "oddish",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png",
    stage: 1,
    colors: ["blue", "green"],
    habitat: "grassland",
    height: 5,
    weight: 54,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 44,
    name: "gloom",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png",
    stage: 2,
    colors: ["blue", "red"],
    habitat: "grassland",
    height: 8,
    weight: 86,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 45,
    name: "vileplume",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png",
    stage: 3,
    colors: ["blue", "red"],
    habitat: "grassland",
    height: 12,
    weight: 186,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 46,
    name: "paras",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png",
    stage: 1,
    colors: ["orange"],
    habitat: "forest",
    height: 3,
    weight: 54,
    type_1: "bug",
    type_2: "grass",
  },
  {
    number: 47,
    name: "parasect",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png",
    stage: 2,
    colors: ["orange"],
    habitat: "forest",
    height: 10,
    weight: 295,
    type_1: "bug",
    type_2: "grass",
  },
  {
    number: 48,
    name: "venonat",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png",
    stage: 1,
    colors: ["purple"],
    habitat: "forest",
    height: 10,
    weight: 300,
    type_1: "bug",
    type_2: "poison",
  },
  {
    number: 49,
    name: "venomoth",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png",
    stage: 2,
    colors: ["purple"],
    habitat: "forest",
    height: 15,
    weight: 125,
    type_1: "bug",
    type_2: "poison",
  },
  {
    number: 50,
    name: "diglett",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png",
    stage: 1,
    colors: ["brown"],
    habitat: "cave",
    height: 2,
    weight: 8,
    type_1: "ground",
    type_2: "none",
  },
  {
    number: 51,
    name: "dugtrio",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png",
    stage: 2,
    colors: ["brown"],
    habitat: "cave",
    height: 7,
    weight: 333,
    type_1: "ground",
    type_2: "none",
  },
  {
    number: 52,
    name: "meowth",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "urban",
    height: 4,
    weight: 42,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 53,
    name: "persian",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "urban",
    height: 10,
    weight: 320,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 54,
    name: "psyduck",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "waters-edge",
    height: 8,
    weight: 196,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 55,
    name: "golduck",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png",
    stage: 2,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 17,
    weight: 766,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 56,
    name: "mankey",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png",
    stage: 1,
    colors: ["white"],
    habitat: "mountain",
    height: 5,
    weight: 280,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 57,
    name: "primeape",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png",
    stage: 2,
    colors: ["white"],
    habitat: "mountain",
    height: 10,
    weight: 320,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 58,
    name: "growlithe",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png",
    stage: 1,
    colors: ["orange"],
    habitat: "grassland",
    height: 7,
    weight: 190,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 59,
    name: "arcanine",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png",
    stage: 2,
    colors: ["orange"],
    habitat: "grassland",
    height: 19,
    weight: 1550,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 60,
    name: "poliwag",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png",
    stage: 1,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 6,
    weight: 124,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 61,
    name: "poliwhirl",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png",
    stage: 2,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 10,
    weight: 200,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 62,
    name: "poliwrath",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png",
    stage: 3,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 13,
    weight: 540,
    type_1: "water",
    type_2: "fighting",
  },
  {
    number: 63,
    name: "abra",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "urban",
    height: 9,
    weight: 195,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 64,
    name: "kadabra",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "urban",
    height: 13,
    weight: 565,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 65,
    name: "alakazam",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png",
    stage: 3,
    colors: ["yellow"],
    habitat: "urban",
    height: 15,
    weight: 480,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 66,
    name: "machop",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
    stage: 1,
    colors: ["gray"],
    habitat: "mountain",
    height: 8,
    weight: 195,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 67,
    name: "machoke",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png",
    stage: 2,
    colors: ["gray"],
    habitat: "mountain",
    height: 15,
    weight: 705,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 68,
    name: "machamp",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png",
    stage: 3,
    colors: ["gray"],
    habitat: "mountain",
    height: 16,
    weight: 1300,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 69,
    name: "bellsprout",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png",
    stage: 1,
    colors: ["green"],
    habitat: "forest",
    height: 7,
    weight: 40,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 70,
    name: "weepinbell",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png",
    stage: 2,
    colors: ["green"],
    habitat: "forest",
    height: 10,
    weight: 64,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 71,
    name: "victreebel",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png",
    stage: 3,
    colors: ["green"],
    habitat: "forest",
    height: 17,
    weight: 155,
    type_1: "grass",
    type_2: "poison",
  },
  {
    number: 72,
    name: "tentacool",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png",
    stage: 1,
    colors: ["blue", "red"],
    habitat: "sea",
    height: 9,
    weight: 455,
    type_1: "water",
    type_2: "poison",
  },
  {
    number: 73,
    name: "tentacruel",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png",
    stage: 2,
    colors: ["blue", "red"],
    habitat: "sea",
    height: 16,
    weight: 550,
    type_1: "water",
    type_2: "poison",
  },
  {
    number: 74,
    name: "geodude",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
    stage: 1,
    colors: ["brown"],
    habitat: "mountain",
    height: 4,
    weight: 200,
    type_1: "rock",
    type_2: "ground",
  },
  {
    number: 75,
    name: "graveler",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png",
    stage: 2,
    colors: ["brown"],
    habitat: "mountain",
    height: 10,
    weight: 1050,
    type_1: "rock",
    type_2: "ground",
  },
  {
    number: 76,
    name: "golem",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png",
    stage: 3,
    colors: ["brown"],
    habitat: "mountain",
    height: 14,
    weight: 3000,
    type_1: "rock",
    type_2: "ground",
  },
  {
    number: 77,
    name: "ponyta",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "grassland",
    height: 10,
    weight: 300,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 78,
    name: "rapidash",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "grassland",
    height: 17,
    weight: 950,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 79,
    name: "slowpoke",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png",
    stage: 1,
    colors: ["pink"],
    habitat: "waters-edge",
    height: 12,
    weight: 360,
    type_1: "water",
    type_2: "psychic",
  },
  {
    number: 80,
    name: "slowbro",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png",
    stage: 2,
    colors: ["pink"],
    habitat: "waters-edge",
    height: 16,
    weight: 785,
    type_1: "water",
    type_2: "psychic",
  },
  {
    number: 81,
    name: "magnemite",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png",
    stage: 1,
    colors: ["gray"],
    habitat: "rough-terrain",
    height: 3,
    weight: 60,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 82,
    name: "magneton",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png",
    stage: 2,
    colors: ["gray"],
    habitat: "rough-terrain",
    height: 10,
    weight: 600,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 83,
    name: "farfetchd",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png",
    stage: 1,
    colors: ["brown"],
    habitat: "grassland",
    height: 8,
    weight: 150,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 84,
    name: "doduo",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png",
    stage: 1,
    colors: ["brown"],
    habitat: "grassland",
    height: 14,
    weight: 392,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 85,
    name: "dodrio",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png",
    stage: 2,
    colors: ["brown"],
    habitat: "grassland",
    height: 18,
    weight: 852,
    type_1: "normal",
    type_2: "flying",
  },
  {
    number: 86,
    name: "seel",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png",
    stage: 1,
    colors: ["white"],
    habitat: "sea",
    height: 11,
    weight: 900,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 87,
    name: "dewgong",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png",
    stage: 2,
    colors: ["white"],
    habitat: "sea",
    height: 17,
    weight: 1200,
    type_1: "water",
    type_2: "ice",
  },
  {
    number: 88,
    name: "grimer",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png",
    stage: 1,
    colors: ["purple"],
    habitat: "urban",
    height: 9,
    weight: 300,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 89,
    name: "muk",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png",
    stage: 2,
    colors: ["purple"],
    habitat: "urban",
    height: 12,
    weight: 300,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 90,
    name: "shellder",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png",
    stage: 1,
    colors: ["purple"],
    habitat: "sea",
    height: 3,
    weight: 40,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 91,
    name: "cloyster",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png",
    stage: 2,
    colors: ["purple"],
    habitat: "sea",
    height: 15,
    weight: 1325,
    type_1: "water",
    type_2: "ice",
  },
  {
    number: 92,
    name: "gastly",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
    stage: 1,
    colors: ["purple"],
    habitat: "cave",
    height: 13,
    weight: 1,
    type_1: "ghost",
    type_2: "poison",
  },
  {
    number: 93,
    name: "haunter",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png",
    stage: 2,
    colors: ["purple"],
    habitat: "cave",
    height: 16,
    weight: 1,
    type_1: "ghost",
    type_2: "poison",
  },
  {
    number: 94,
    name: "gengar",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
    stage: 3,
    colors: ["purple"],
    habitat: "cave",
    height: 15,
    weight: 405,
    type_1: "ghost",
    type_2: "poison",
  },
  {
    number: 95,
    name: "onix",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png",
    stage: 1,
    colors: ["gray"],
    habitat: "cave",
    height: 88,
    weight: 2100,
    type_1: "rock",
    type_2: "ground",
  },
  {
    number: 96,
    name: "drowzee",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "grassland",
    height: 10,
    weight: 324,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 97,
    name: "hypno",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "grassland",
    height: 16,
    weight: 756,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 98,
    name: "krabby",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png",
    stage: 1,
    colors: ["red"],
    habitat: "waters-edge",
    height: 4,
    weight: 65,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 99,
    name: "kingler",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png",
    stage: 2,
    colors: ["red"],
    habitat: "waters-edge",
    height: 13,
    weight: 600,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 100,
    name: "voltorb",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png",
    stage: 1,
    colors: ["red", "white"],
    habitat: "urban",
    height: 5,
    weight: 104,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 101,
    name: "electrode",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png",
    stage: 2,
    colors: ["red", "white"],
    habitat: "urban",
    height: 12,
    weight: 666,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 102,
    name: "exeggcute",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png",
    stage: 1,
    colors: ["pink"],
    habitat: "forest",
    height: 4,
    weight: 25,
    type_1: "grass",
    type_2: "psychic",
  },
  {
    number: 103,
    name: "exeggutor",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "forest",
    height: 20,
    weight: 1200,
    type_1: "grass",
    type_2: "psychic",
  },
  {
    number: 104,
    name: "cubone",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png",
    stage: 1,
    colors: ["brown"],
    habitat: "mountain",
    height: 4,
    weight: 65,
    type_1: "ground",
    type_2: "none",
  },
  {
    number: 105,
    name: "marowak",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png",
    stage: 2,
    colors: ["brown"],
    habitat: "mountain",
    height: 10,
    weight: 450,
    type_1: "ground",
    type_2: "none",
  },
  {
    number: 106,
    name: "hitmonlee",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png",
    stage: 1,
    colors: ["brown"],
    habitat: "urban",
    height: 15,
    weight: 498,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 107,
    name: "hitmonchan",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png",
    stage: 1,
    colors: ["brown"],
    habitat: "urban",
    height: 14,
    weight: 502,
    type_1: "fighting",
    type_2: "none",
  },
  {
    number: 108,
    name: "lickitung",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png",
    stage: 1,
    colors: ["pink"],
    habitat: "grassland",
    height: 12,
    weight: 655,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 109,
    name: "koffing",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png",
    stage: 1,
    colors: ["purple"],
    habitat: "urban",
    height: 6,
    weight: 10,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 110,
    name: "weezing",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png",
    stage: 2,
    colors: ["purple"],
    habitat: "urban",
    height: 12,
    weight: 95,
    type_1: "poison",
    type_2: "none",
  },
  {
    number: 111,
    name: "rhyhorn",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png",
    stage: 1,
    colors: ["gray"],
    habitat: "rough-terrain",
    height: 10,
    weight: 1150,
    type_1: "ground",
    type_2: "rock",
  },
  {
    number: 112,
    name: "rhydon",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png",
    stage: 2,
    colors: ["gray"],
    habitat: "rough-terrain",
    height: 19,
    weight: 1200,
    type_1: "ground",
    type_2: "rock",
  },
  {
    number: 113,
    name: "chansey",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png",
    stage: 1,
    colors: ["pink"],
    habitat: "urban",
    height: 11,
    weight: 346,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 114,
    name: "tangela",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png",
    stage: 1,
    colors: ["blue"],
    habitat: "grassland",
    height: 10,
    weight: 350,
    type_1: "grass",
    type_2: "none",
  },
  {
    number: 115,
    name: "kangaskhan",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png",
    stage: 1,
    colors: ["brown"],
    habitat: "grassland",
    height: 22,
    weight: 800,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 116,
    name: "horsea",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png",
    stage: 1,
    colors: ["blue"],
    habitat: "sea",
    height: 4,
    weight: 80,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 117,
    name: "seadra",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png",
    stage: 2,
    colors: ["blue"],
    habitat: "sea",
    height: 12,
    weight: 250,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 118,
    name: "goldeen",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png",
    stage: 1,
    colors: ["orange", "white"],
    habitat: "waters-edge",
    height: 6,
    weight: 150,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 119,
    name: "seaking",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png",
    stage: 2,
    colors: ["orange", "white"],
    habitat: "waters-edge",
    height: 13,
    weight: 390,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 120,
    name: "staryu",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png",
    stage: 1,
    colors: ["brown", "red"],
    habitat: "sea",
    height: 8,
    weight: 345,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 121,
    name: "starmie",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png",
    stage: 2,
    colors: ["purple", "red"],
    habitat: "sea",
    height: 11,
    weight: 800,
    type_1: "water",
    type_2: "psychic",
  },
  {
    number: 122,
    name: "mr-mime",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png",
    stage: 1,
    colors: ["pink"],
    habitat: "urban",
    height: 13,
    weight: 545,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 123,
    name: "scyther",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png",
    stage: 1,
    colors: ["green"],
    habitat: "grassland",
    height: 15,
    weight: 560,
    type_1: "bug",
    type_2: "flying",
  },
  {
    number: 124,
    name: "jynx",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png",
    stage: 1,
    colors: ["purple"],
    habitat: "urban",
    height: 14,
    weight: 406,
    type_1: "ice",
    type_2: "psychic",
  },
  {
    number: 125,
    name: "electabuzz",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "grassland",
    height: 11,
    weight: 300,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 126,
    name: "magmar",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png",
    stage: 1,
    colors: ["orange"],
    habitat: "mountain",
    height: 13,
    weight: 445,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 127,
    name: "pinsir",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png",
    stage: 1,
    colors: ["brown"],
    habitat: "forest",
    height: 15,
    weight: 550,
    type_1: "bug",
    type_2: "none",
  },
  {
    number: 128,
    name: "tauros",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png",
    stage: 1,
    colors: ["brown"],
    habitat: "grassland",
    height: 14,
    weight: 884,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 129,
    name: "magikarp",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png",
    stage: 1,
    colors: ["red"],
    habitat: "waters-edge",
    height: 9,
    weight: 100,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 130,
    name: "gyarados",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
    stage: 2,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 65,
    weight: 2350,
    type_1: "water",
    type_2: "flying",
  },
  {
    number: 131,
    name: "lapras",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
    stage: 1,
    colors: ["blue"],
    habitat: "sea",
    height: 25,
    weight: 2200,
    type_1: "water",
    type_2: "ice",
  },
  {
    number: 132,
    name: "ditto",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png",
    stage: 1,
    colors: ["purple"],
    habitat: "urban",
    height: 3,
    weight: 40,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 133,
    name: "eevee",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
    stage: 1,
    colors: ["brown"],
    habitat: "urban",
    height: 3,
    weight: 65,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 134,
    name: "vaporeon",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
    stage: 2,
    colors: ["blue"],
    habitat: "urban",
    height: 10,
    weight: 290,
    type_1: "water",
    type_2: "none",
  },
  {
    number: 135,
    name: "jolteon",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png",
    stage: 2,
    colors: ["yellow"],
    habitat: "urban",
    height: 8,
    weight: 245,
    type_1: "electric",
    type_2: "none",
  },
  {
    number: 136,
    name: "flareon",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png",
    stage: 2,
    colors: ["orange"],
    habitat: "urban",
    height: 9,
    weight: 250,
    type_1: "fire",
    type_2: "none",
  },
  {
    number: 137,
    name: "porygon",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png",
    stage: 1,
    colors: ["pink", "blue"],
    habitat: "urban",
    height: 8,
    weight: 365,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 138,
    name: "omanyte",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png",
    stage: 1,
    colors: ["blue"],
    habitat: "sea",
    height: 4,
    weight: 75,
    type_1: "rock",
    type_2: "water",
  },
  {
    number: 139,
    name: "omastar",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png",
    stage: 2,
    colors: ["blue"],
    habitat: "sea",
    height: 10,
    weight: 350,
    type_1: "rock",
    type_2: "water",
  },
  {
    number: 140,
    name: "kabuto",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png",
    stage: 1,
    colors: ["brown"],
    habitat: "sea",
    height: 5,
    weight: 115,
    type_1: "rock",
    type_2: "water",
  },
  {
    number: 141,
    name: "kabutops",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png",
    stage: 2,
    colors: ["brown"],
    habitat: "sea",
    height: 13,
    weight: 405,
    type_1: "rock",
    type_2: "water",
  },
  {
    number: 142,
    name: "aerodactyl",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png",
    stage: 1,
    colors: ["purple"],
    habitat: "mountain",
    height: 18,
    weight: 590,
    type_1: "rock",
    type_2: "flying",
  },
  {
    number: 143,
    name: "snorlax",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
    stage: 1,
    colors: ["black"],
    habitat: "mountain",
    height: 21,
    weight: 4600,
    type_1: "normal",
    type_2: "none",
  },
  {
    number: 144,
    name: "articuno",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
    stage: 1,
    colors: ["blue"],
    habitat: "rare",
    height: 17,
    weight: 554,
    type_1: "ice",
    type_2: "flying",
  },
  {
    number: 145,
    name: "zapdos",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
    stage: 1,
    colors: ["yellow"],
    habitat: "rare",
    height: 16,
    weight: 526,
    type_1: "electric",
    type_2: "flying",
  },
  {
    number: 146,
    name: "moltres",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png",
    stage: 1,
    colors: ["orange"],
    habitat: "rare",
    height: 20,
    weight: 600,
    type_1: "fire",
    type_2: "flying",
  },
  {
    number: 147,
    name: "dratini",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
    stage: 1,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 18,
    weight: 33,
    type_1: "dragon",
    type_2: "none",
  },
  {
    number: 148,
    name: "dragonair",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png",
    stage: 2,
    colors: ["blue"],
    habitat: "waters-edge",
    height: 40,
    weight: 165,
    type_1: "dragon",
    type_2: "none",
  },
  {
    number: 149,
    name: "dragonite",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
    stage: 3,
    colors: ["orange"],
    habitat: "waters-edge",
    height: 22,
    weight: 2100,
    type_1: "dragon",
    type_2: "flying",
  },
  {
    number: 150,
    name: "mewtwo",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
    stage: 1,
    colors: ["purple"],
    habitat: "rare",
    height: 20,
    weight: 1220,
    type_1: "psychic",
    type_2: "none",
  },
  {
    number: 151,
    name: "mew",
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
    stage: 1,
    colors: ["pink"],
    habitat: "rare",
    height: 4,
    weight: 40,
    type_1: "psychic",
    type_2: "none",
  },
];

export function getPokemonByNumber(number: number): PokemonData {
  return POKEMONS.find((p) => p.number === number);
}

export type PokemonData = (typeof POKEMONS)[0];
